# Generated by Django 3.0.2 on 2020-01-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('repo', models.CharField(max_length=100)),
                ('source_branch', models.CharField(max_length=100)),
                ('target_branch', models.CharField(max_length=100)),
                ('target_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
