# Generated by Django 3.0.2 on 2020-01-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mergerequest_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergerequest',
            name='target_email',
            field=models.EmailField(max_length=100),
        ),
    ]
