# Generated by Django 3.0.2 on 2020-01-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200121_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergerequest',
            name='status',
            field=models.CharField(default='Open', max_length=100),
        ),
    ]
