# Generated by Django 3.0.2 on 2020-01-21 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mergerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergerequest',
            name='date_opened',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
