# Generated by Django 3.0.2 on 2020-01-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mergerequest_date_opened'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergerequest',
            name='source_branch',
        ),
        migrations.RemoveField(
            model_name='mergerequest',
            name='target_branch',
        ),
    ]
