# Generated by Django 3.0.2 on 2020-01-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200121_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergerequest',
            name='source_branch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mergerequest',
            name='target_branch',
            field=models.CharField(default='', max_length=100),
        ),
    ]
