# Generated by Django 3.0.2 on 2020-01-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200127_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergerequest',
            name='repo',
            field=models.CharField(choices=[], default='', max_length=100),
        ),
    ]
