# Generated by Django 3.0.2 on 2020-01-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200127_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergerequest',
            name='repo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mergerequest',
            name='source_branch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mergerequest',
            name='target_branch',
            field=models.CharField(default='', max_length=100),
        ),
    ]
